### PR TITLE
nodejs: port the nodejs CoreIpc lib to Linux

### PR DESCRIPTION
**Pull request by eduard-dumitru**
## nodejs:
- commission a class hierarchy (called `CoreIpcPlatform`) as an aggregator for various strategies to hide differences between "Linux + .Net Core" and Windows
  - the list of strategies is open-ended
  - implement the following operations:
     1. `getFullName(shortName: string): string` will translate `"pipe123"` to either `"\\.\pipe\pipe123"` or `"/tmp/CoreFxPipe_pipe123"`
     2. `pipeExists(shortName: string): Promise<boolean>` will either use the filesystem (on Windows) or will try to connect (Linux) in order to check the availability of a certain pipe (checking the filesystem on Linux may give false positive after server shutdown)
     3. `getDefaultDotNet(): string` - used only in unit tests - gives the `dotnet.exe` / `dotnet` name which should be passed to `child_process.spawn` in order to start a .NET Core process
     4. `useShellInUnitTests(): boolean` - used only in unit tests - is a switch for using / not using ShellExecute when launching .NET Core CoreIpc servers
- update the nodejs Readme.md

## Azure Pipelines:
- split the `nodejs` AZP Job in two: `"nodejs on Windows"` and `"nodejs on Ubuntu"`
- leave the `.NET` AZP Job as it is but rename it to `".NET on Windows"`
- make it so that `"nodejs on Ubuntu"` doesn't publish any distributable artifacts (it will publish however coverage and test results)
- individually build the 2 projects within `UiPath.Core.NodeInterop.sln`:
  - by explicitly specifying `--framework netstandard2.0` for `UiPath.CoreIpc.csproj` 
  - and `--framework netcoreapp3.1` for `UiPath.CoreIpc.NodeInterop.csproj` 

## file tree moves:
- move the entire nodejs lib source code from `./src/Clients/nodejs/**` to `./src/Clients/nodejs/core/**` in order to accommodate the playground app at `./src/Clients/nodejs/playground/**`
- move `UiPath.CoreIpc.NodeInterop.sln` into `./src/Clients/nodejs/dotnet-interop/**`

### CODE REVIEW

**Comment by eduard-dumitru** [comment]
@lbargaoanu Have a look at these changes:

1. I needed to make MSBuild not fail on Linux because it can't build .NET Framework and believe this is the simplest solution: https://github.com/UiPath/coreipc/blob/8885081ccb1c478b1f770b7c84d5e63d5cea0285/src/UiPath.CoreIpc/UiPath.CoreIpc.csproj#L3

2. I created this folder here (not forever, could be deleted right away, what do you think?):
https://github.com/UiPath/coreipc/tree/feature/torvalds/src/Clients/nodejs-playground

This is a manual test app, similar in nature to `IpcSample.ConsoleClient`. NodeJS is a fragile place and I couldn't just put it inside the existing `nodejs` folder. They could both become children of an extra intermediate `nodejs` parent if you think the file tree looks awful. I'm only asking because not doing that saves some AZP yaml changes and tests.

**Review by danutboanta — APPROVED** [review]

**Pull request merged**
